<div class="container">
	<div class="row">
		<div class="col col-md-12 margin-bottom-20">
			
			<h4 class="page_title"><?php echo $title; ?></h4>
			
			<article class="privacy-policy">			    
			    <p>This privacy policy sets out how Sound Decisions uses and protects any information that you give Sound Decisions when you use this website.</p>
			    <p>Sound Decisions is committed to ensuring that your privacy is protected. 
			        Should we ask you to provide certain information by which you can be identified when using this website, then you can be assured that it will only be used in accordance with this privacy statement.</p>
			    <p>Sound Decisions may change this policy from time to time by updating this page. 
			        You should check this page from time to time to ensure that you are happy with any changes.</p>
			    <p>This policy is effective from 2002-03-03.</p>    
			    <h4>What we collect</h4>
			    <p>We collect certain personal information about the visitor during the sign up/registration process so we can identify the user when signing into our site and to secure their information.
			        In addition to that we also use Google Analytics. 
			        More info about Google Analytics you can find below.</p>
			    <h4>How we use cookies</h4>
			    <p>A cookie is a small file which asks permission to be placed on your computer's hard drive. 
			        Once you agree, the file is added and the cookie helps analyse web traffic or lets you know when you visit a particular site. 
			        Cookies allow web applications to respond to you as an individual. 
			        The web application can tailor its operations to your needs, likes and dislikes by gathering and remembering information about your preferences.
			        We do use cookies for saving settings on this website. We do not save any other personal information in our cookies.</p>
			    <h4>Links to other websites</h4>
			    <p>Our website may contain links to other websites of interest. 
			        However, once you have used these links to leave our sites, you should note that we do not have any control over that other website. 
			        Therefore, we cannot be responsible for the protection and privacy of any information which you provide whilst visiting such sites and such sites are not governed by this privacy statement. 
			        You should exercise caution and look at the privacy statement applicable to the website in question.</p>
			    <h4>Google Analytics Disclaimer</h4>
			    <p>This website uses Google Analytics, a web analytics service provided by Google, Inc. ("Google"). 
			        Google Analytics uses "cookies", which are text files placed on your computer, to help the website analyze how users use the site. 
			        The information generated by the cookie about your use of the website (including your IP address) will be transmitted to and stored by Google on servers in the United States . 
			        Google will use this information for the purpose of evaluating your use of the website, compiling reports on website activity for website operators and providing other services relating to website activity and internet usage. 
			        Google may also transfer this information to third parties where required to do so by law, or where such third parties process the information on Google's behalf. 
			        Google will not associate your IP address with any other data held by Google. 
			        You may refuse the use of cookies by selecting the appropriate settings on your browser, however please note that if you do this you may not be able to use the full functionality of this website. 
			        By using this website, you consent to the processing of data about you by Google in the manner and for the purposes set out above.</p>
			</article>			
			
		</div><!-- end of - col col-md-12-->
	</div><!-- end of - row -->
</div><!-- end of - container -->